[package]
name = "urlshortener_codec"
version = "0.0.1"
authors = ["Saju Thankappan <sajuthankappan@gmail.com>"]
description = "Urlshortener encode/decode"
license = "MIT"
repository = "https://github.com/sajuthankappan/urlshortener-codec-rs"
