[package]
name = "urlshortener_converter"
version = "0.0.1"
authors = ["Saju Thankappan <sajuthankappan@gmail.com>"]
description = "Encoding and decoding of short url ids for url shortener applications"
license = "MIT"
repository = "https://github.com/sajuthankappan/urlshortener-converter-rs"
