[package]
name = "urlshortener_codec"
version = "0.1.0"
authors = ["Saju Thankappan <sajuthankappan@gmail.com>"]
description = "Urlshortener encode/decode"
license = "MIT OR Apache-2.0"
repository = "https://github.com/sajuthankappan/urlshortener-codec-rs"
